---
- name: Install fuse [Ubuntu]
  apt:
    name: fuse
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: make cvmfs dir
  shell:
    cmd: mkdir -p /cvmfs
    creates: /cvmfs

- name: prepare variable for cvmfs
  set_fact:
    key_value: "yes"
    cvmfs_service: |
      cvmfs:
          image: dodasts/cvmfs:latest
          privileged: true
          volumes:
            - type: bind
              source: /cvmfs
              target: /cvmfs
              bind:
                propagation: rshared
          environment:
            - REPO_LIST={{ cvmfs_repos }}

- name: prepare compose variable for cvmfs
  set_fact:
    key_value: "yes"
    jupyter_with_cvmfs: true
