---
- name: install docker [Debian]
  include_tasks: Debian-docker.yml
  when: ansible_facts.os_family == "Debian"

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install nvidia driver and container toolkit [Debian]
  include_tasks: Debian-nvidia-stuff.yml
  when: ansible_facts.os_family == "Debian"

- name: restart docker service
  systemd:
    name: docker
    state: restarted
