---
# tasks file for ansible-role-nvidia-docker
# - name: Install gcc
#   apt:
#     name: gcc
#     state: present
#     autoclean: yes
#     autoremove: yes
#     update_cache: yes

# - name: Install make
#   apt:
#     name: make
#     state: present
#     autoclean: yes
#     autoremove: yes
#     update_cache: yes

- name: install docker [Debian]
  include: Debian-docker.yaml"
  static: false
  when: ansible_facts.os_family == "Debian"

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install nvidia driver and container toolkit [Debian]
  include: Debian-nvidia-stuff.yaml"
  static: false
  when: ansible_facts.os_family == "Debian"

- name: restart docker service
  systemd:
    name: docker
    state: restarted
