---
# ---------- check OS ----------
- name: Check OS
  ansible.builtin.fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu' and ansible_os_family != 'RedHat'

- name: Check if GPU is used
  ansible.builtin.set_fact:
    key_value: "yes"
    use_gpu: yes
  when: ((jupyter_use_gpu | bool) or (jupyterlab_collaborative_use_gpu | bool))

# ---------- Update Ubuntu ----------
- name: Update [Ubuntu]
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

# ---------- Docker ----------
- name: Install docker [Ubuntu]
  ansible.builtin.include_tasks: Ubuntu-docker.yml
  when: (install_docker | bool) and ansible_facts['distribution'] == "Ubuntu"

- name: start and enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

# ---------- Docker compose ----------
- name: Install docker compose [Ubuntu]
  ansible.builtin.include_tasks: Ubuntu-docker-compose.yml
  when: (install_docker_compose | bool) and ansible_facts['distribution'] == "Ubuntu"


# ---------- GPU support ----------
- name: Add GPU support
  # include_tasks: nvidia-driver-and-toolkit.yml
  ansible.builtin.include_tasks: gpu-support.yaml
  vars:
    enable_gpu: true
    gpu_support_role: git+https://baltig.infn.it/infn-cloud/ansible-role-gpu-support,v1.0.0
    nvidia_driver_branch: "515"
    nvidia_driver_ubuntu_install_from_cuda_repo: true
    nvidia_driver_skip_reboot: true
  when: (use_gpu | bool)

# ---------- reload docker service ----------
- name: Reload docker service
  ansible.builtin.systemd:
    name: docker
    # Force reload
    state: reloaded

# ---------- Setup CVMFS ----------
- name: Setup CVMFS
  ansible.builtin.include_tasks: cvmfs.yml
  when: cvmfs_repos|length > 0

# ---------- Jupyter hub ----------
- name: Prepare Jupyter Hub
  ansible.builtin.include_tasks: prepare-jupyter-hub.yml

# ---------- configure docker compose environment ----------
- name: Configure docker compose environment
  ansible.builtin.include_tasks: configure-compose-environment.yml

- name: Run Jupyter Hub
  ansible.builtin.shell:
    cmd: docker-compose up -d
    chdir: /usr/local/share/dodasts/jupyterhub
  when: (run_jupyter | bool)

  # ---------- Setup monitoring ----------
- name: Setup monitoring
  ansible.builtin.include_tasks: monitoring.yml
  when: (monitoring | bool)
