---
# tasks file for ansible-role-nvidia-docker
- name: Install gcc
  apt:
    name: gcc
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes

- name: Install make
  apt:
    name: make
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes

- name: install docker [Debian]
  shell:
    cmd: curl https://get.docker.com | sh
    # creates: """
  when: ansible_facts.os_family == "Debian"
