---
# tasks file for ansible-role-nvidia-docker
- name: Install gcc
  apt:
    name: gcc
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes

- name: Install make
  apt:
    name: make
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes
