---
# ---------- check OS ----------
- name: check OS
  fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu' and ansible_os_family != 'RedHat'

# ---------- Gen nvidia driver role ----------
- name: get nvidia.nvidia_driver role
  shell:
    cmd: ansible-galaxy install -f -p /tmp/roles nvidia.nvidia_driver

# ---------- Fix reboot cmd ----------
# Only supported in Ansible >= 2.7
- name: get nvidia.nvidia_driver role
  replace:
    path: /tmp/roles/nvidia.nvidia_driver/tasks/main.yml
    regexp: 'reboot\:'
    replace: "shell: reboot"
  when: ansible_version.major == 2 and ansible_version.minor < 7

# ---------- Docker ----------
- name: install docker [Ubuntu]
  include_tasks: Ubuntu-docker.yml
  when: docker.install and ansible_facts['distribution'] == "Ubuntu"

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# ---------- Docker compose ----------
- name: install docker compose [Ubuntu]
  include_tasks: Ubuntu-docker-compose.yml
  when: docker.compose.install and ansible_facts['distribution'] == "Ubuntu"

# ---------- Nvidia Driver ----------
- name: install nvidia driver [RedHat]
  role:
    name: /tmp/roles/nvidia.nvidia_driver
  vars:
    nvidia_driver_skip_reboot: nvidia.skip_reboot
  when: nvidia.driver.install and "ansible_facts['os_family'] == 'RedHat'"

- name: install nvidia driver [Ubuntu]
  role:
    name: /tmp/roles/nvidia.nvidia_driver
  vars:
    nvidia_driver_skip_reboot: nvidia.skip_reboot
    nvidia_driver_ubuntu_install_from_cuda_repo: nvidia.driver.from_cuda
  when: nvidia.driver.install and ansible_facts['distribution'] == 'Ubuntu'

# ---------- Nvidia Container Toolkit ----------
- name: install nvidia container toolkit [Ubuntu]
  include_tasks: Ubuntu-nvidia-container-toolkit.yml
  when: nvidia.container.install and ansible_facts['distribution'] == 'Ubuntu'

- name: restart docker service
  systemd:
    name: docker
    state: restarted
