---
# ---------- check OS ----------
- name: check OS
  fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu' and ansible_os_family != 'RedHat'

# ---------- Docker ----------
- name: install docker [Ubuntu]
  include_tasks: Ubuntu-docker.yml
  when: (install_docker | bool) and ansible_facts['distribution'] == "Ubuntu"

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

# ---------- Docker compose ----------
- name: install docker compose [Ubuntu]
  include_tasks: Ubuntu-docker-compose.yml
  when: (install_docker_compose | bool) and ansible_facts['distribution'] == "Ubuntu"

# ---------- Nvidia stuff ----------
- name: Nvidia stuff
  include_tasks: nvidia-driver-and-toolkit.yml
  when: (use_gpu | bool)

# ---------- Setup monitoring ----------
- name: Setup monitoring
  include_tasks: monitoring.yml
  when: (monitoring | bool)

# ---------- Jupyter hub ----------
- name: prepare Jupyter Hub
  include_tasks: prepare-jupyter-hub.yml
  when: (prepare_jupyter | bool)

- name: run Jupyter Hub
  shell:
    cmd: docker-compose up -d
    chdir: /usr/local/MLinD-INFN
  when: (run_jupyter | bool)
