---
# ---------- Install IAM client ----------
- name: Install golang
  shell:
    cmd: |
      wget https://golang.org/dl/go1.16.linux-amd64.tar.gz \
      && tar -C /usr/local -xzf go1.16.linux-amd64.tar.gz \
      && echo "export GOROOT=/usr/local/go" >> /etc/profile.d/go.sh \
      && echo "export GOPATH=/opt/go" >> /etc/profile.d/go.sh \
      && echo "export PATH=/usr/local/go/bin:/opt/go/bin:$PATH" >> /etc/profile.d/go.sh \
      && ln -s /usr/local/go/bin/* /usr/local/bin/
    chdir: /tmp
    creates:
      - /etc/profile.d/go.sh
      - /usr/local/bin/go

# ---------- Self signed certificates ----------
- name: download dodas-x509
  git:
    repo: "https://github.com/DODAS-TS/dodas-x509.git"
    dest: /usr/local/share/dodasts/dodas-x509
    force: yes

- name: compile dodas-x509
  shell:
    cmd: go get github.com/dodas-ts/dodas-x509/pkg/v1 && go build
    chdir: /usr/local/share/dodasts/dodas-x509

- name: link executable dodas-x509
  shell:
    cmd: ln -s /usr/local/share/dodasts/dodas-x509/dodas-x509 /usr/local/bin/dodas-x509
    creates: /usr/local/bin/dodas-x509

- name: create certificates
  shell:
    cmd: |
      dodas-x509 --generate-all --hostname {{server_ip}} \
      && mkdir -p /tmp/certs/jupyter \
      && mkdir -p /tmp/certs/grafana \
      && cp /tmp/hostcert.* /tmp/certs/jupyter \
      && cp /tmp/hostcert.* /tmp/certs/grafana \
      && chown -R 472:472 /tmp/certs/grafana \
      && chown -R nobody:nogroup /tmp/certs/jupyter
    creates:
      - /tmp/certs/hostcert.pem
      - /tmp/certs/hostcert.key
