---
- name: download monitoring role
  git:
    repo: "https://github.com/DODAS-TS/ansible-role-monitoring.git"
    dest: /etc/ansible/roles/ansible-role-monitoring
    force: yes
    version: v1.1.0

# ---------- Execute monitoring role ----------
- name: Execute monitoring role
  include_role:
    name: /etc/ansible/roles/ansible-role-monitoring
  vars:
    monitoring_project_name: "single_node_jupyterhub"
    monitoring_server_ip: "{{ server_ip }}"
    monitoring_iam_sub:  "{{ iam_subject }}"
    monitoring_iam_url: "{{ iam_url }}"
    monitoring_iam_groups: "{{ iam_groups }}"
    monitoring_iam_admin_groups: "{{ iam_admin_groups }}"
    service_grafana: "{{ grafana }}"
    service_grafana_port: "{{ grafana_port }}"
    service_grafana_admin_user: "{{ grafana_admin_user }}"
    service_grafana_admin_password: "{{ grafana_admin_password }}"
    service_grafana_client_id: "{{ grafana_client_id }}"
    service_grafana_client_secret: "{{ grafana_client_secret }}"
    service_grafana_image: "{{ grafana_image }}"
