---
# ---------- Create directory for monitoring ----------
- name: Create directory for monitoring
  file:
    path: /usr/local/share/monitoring
    state: directory

# ---------- Create directory for grafana ----------
- name: Create directory for grafana
  file:
    path: /usr/local/share/monitoring/grafana
    state: directory

# ---------- Create grafana configs ----------
- name: Create grafana configs
  copy:
    src: "{{ role_path }}/files/grafana"
    dest: /usr/local/share/monitoring
    directory_mode: 0755

# ---------- Enable monitoring also with nvidia ----------
- name: prepare variables for monitoring
  set_fact:
    key_value: "yes"
    grafana_service: |
      grafana:
          image: grafana/grafana:latest
          container_name: monitoring_grafana
          restart: unless-stopped
          command:
          - "-config"
          - "/opt/grafana/custom.ini"
          links:
            - prometheus:prometheus
          ports:
          - 3000:3000
          volumes:
          - /usr/local/share/monitoring/grafana/config:/opt/grafana/
          - /usr/local/share/monitoring/grafana/config/provisioning:/etc/grafana/provisioning
          - /usr/local/share/monitoring/grafana/dash_models:/opt/dash_models
          environment:
            - GF_SECURITY_ADMIN_PASSWORD={{grafana_password}}
            - GF_USERS_ALLOW_SIGN_UP=false
    cacheable: yes
