---
# ---------- Create directory for monitoring ----------
- name: Create directory for monitoring
  file:
    path: /usr/local/monitoring
    state: directory

# ---------- Create directory for grafana ----------
- name: Create directory for grafana
  file:
    path: /usr/local/monitoring/grafana
    state: directory

# ---------- Create grafana configs ----------
- name: Create grafana configs
  copy:
    src: "{{ role_path }}/files/grafana"
    dest: /usr/local/monitoring
    directory_mode: yes
