---
# ---------- Enable monitoring also with nvidia ----------
- name: "prepare variables for monitoring"
  set_fact:
    key_value: "yes"
    nvidia_monitoring: |
      nvidia:
          runtime: nvidia
          image: nvidia/dcgm-exporter
          container_name: monitoring_nvidia
          privileged: true
          restart: unless-stopped
          expose:
            - 9400
          #ports:
          #  - 9400:9400
    nvidia_depends: "- nvidia"
    prometheus_nvidia: "- 'monitoring_nvidia:9400'"
    cacheable: yes
  when: (use_gpu | bool)

# ---------- Create directory for monitoring ----------
- name: Create directory for monitoring
  file:
    path: /usr/local/share/dodasts/monitoring
    state: directory
    mode: 0755

# ---------- Create directory for prometheus ----------
- name: Create directory for prometheus
  file:
    path: /usr/local/share/dodasts/monitoring/prometheus
    state: directory
    mode: 0755

# ---------- Create directory for prometheus config ----------
- name: Create directory for prometheus config
  file:
    path: /usr/local/share/dodasts/monitoring/prometheus/config
    state: directory
    mode: 0755

    # ---------- Create directory for prometheus data ----------
- name: Create directory for prometheus data
  file:
    path: /usr/local/share/dodasts/monitoring/prometheus/data
    state: directory
    owner: nobody
    group: nogroup
    mode: 0755

# ---------- Create prometheus config for monitoring from template ----------
- name: Create prometheus config for monitoring from template
  template:
    src: prometheus-config.j2
    dest: /usr/local/share/dodasts/monitoring/prometheus/config/prometheus.yml
