--- # ---------- Enable monitoring also with nvidia ----------
- name: prepare variables for monitoring
  set_fact:
    nvidia_monitoring: |
      nvidia:
          runtime: nvidia
          image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
          container_name: monitoring_nvidia
          privileged: true
          restart: unless-stopped
          expose:
            - 9400
          #ports:
          #  - 9400:9400
    prometheus_nvidia: "- 'nvidia:9400'"
    cacheable: yes
  when: install_nvidia_container_toolkit

# ---------- Enable monitoring without nvidia ----------
- name: prepare variables for monitoring without nvidia
  set_fact:
    nvidia_monitoring: ""
    prometheus_nvidia: ""
    cacheable: yes
  when: not install_nvidia_container_toolkit

# ---------- Create directory for monitoring ----------
- name: Create directory for monitoring
  file:
    path: /usr/local/monitoring
    state: directory

# ---------- Create directory for grafana ----------
- name: Create directory for grafana
  file:
    path: /usr/local/monitoring/grafana
    state: directory

# ---------- Create directory for prometheus ----------
- name: Create directory for prometheus
  file:
    path: /usr/local/monitoring/prometheus
    state: directory

# ---------- Create directory for prometheus config ----------
- name: Create directory for prometheus config
  file:
    path: /usr/local/monitoring/prometheus/config
    state: directory

# ---------- Create docker compose for monitoring from template ----------
- name: Create docker compose for monitoring from template
  template:
    src: monitoring-compose.j2
    dest: /usr/local/monitoring/docker-compose.yaml

# ---------- Create prometheus config for monitoring from template ----------
- name: Create prometheus config for monitoring from template
  template:
    src: prometheus-config.j2
    dest: /usr/local/monitoring/prometheus/config/prometheus.yml

# ---------- Run prometheus ----------
- name: Run prometheus
  shell:
    cmd: docker-compose up -d
    chdir: /usr/local/monitoring
