---
# ---------- Get monitoring role ----------
- name: download dodas-x509
  git:
    repo: "https://github.com/DODAS-TS/ansible-role-monitoring.git"
    dest: /usr/local/share/dodasts/ansible-role-monitoring
    force: yes

# ---------- Execute monitoring role ----------
- name: Execute monitoring role
  include_role:
    name: /usr/local/share/dodasts/ansible-role-monitoring
