---
# ---------- Enable monitoring also with nvidia ----------
- name: "prepare variables for monitoring"
  set_fact:
    key_value: "yes"
    nvidia_monitoring: |
      nvidia:
          runtime: nvidia
          image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
          container_name: monitoring_nvidia
          privileged: true
          restart: unless-stopped
          expose:
            - 9400
          #ports:
          #  - 9400:9400
    prometheus_nvidia: "- 'nvidia:9400'"
    cacheable: yes
  when: use_gpu

# ---------- Enable monitoring without nvidia ----------
- name: "prepare variables for monitoring without nvidia"
  set_fact:
    key_value: "yes"
    nvidia_monitoring: ""
    prometheus_nvidia: ""
    cacheable: yes
  when: not use_gpu

# ---------- Create directory for monitoring ----------
- name: Create directory for monitoring
  file:
    path: /usr/local/monitoring
    state: directory

# ---------- Create directory for prometheus ----------
- name: Create directory for prometheus
  file:
    path: /usr/local/monitoring/prometheus
    state: directory

# ---------- Create directory for prometheus config ----------
- name: Create directory for prometheus config
  file:
    path: /usr/local/monitoring/prometheus/config
    state: directory

    # ---------- Create directory for prometheus data ----------
- name: Create directory for prometheus data
  file:
    path: /usr/local/monitoring/prometheus/data
    state: directory
    mode: "u+rwx,g+wr,o+rw"

# ---------- Create prometheus config for monitoring from template ----------
- name: Create prometheus config for monitoring from template
  template:
    src: prometheus-config.j2
    dest: /usr/local/monitoring/prometheus/config/prometheus.yml
