---
# ---------- Create directory for monitoring ----------
- name: Create directory for monitoring
  file:
    path: /usr/local/share/dodasts/monitoring
    state: directory
    mode: 0755

# ---------- Create directory for grafana ----------
- name: Create directory for grafana
  file:
    path: /usr/local/share/dodasts/monitoring/grafana
    state: directory
    mode: 0755

# ---------- Create grafana configs ----------
- name: Create grafana configs
  copy:
    src: "{{ role_path }}/files/grafana"
    dest: /usr/local/share/dodasts/monitoring
    directory_mode: 0755

- name: download dodas-IAMClientRec
  git:
    repo: "https://github.com/dciangot/dodas-IAMClientRec"
    dest: /usr/local/share/dodasts/dodas-IAMClientRec
    force: yes

- name: compile dodas-IAMClientRec
  shell:
    cmd: go get github.com/dciangot/sts-wire/pkg/core && go build
    chdir: /usr/local/share/dodasts/dodas-IAMClientRec

- name: link executable dodas-IAMClientRec
  shell:
    cmd: ln -s /usr/local/share/dodasts/dodas-IAMClientRec/dodas-IAMClientRec /usr/local/bin/dodas-IAMClientRec
    creates: /usr/local/bin/dodas-IAMClientRec

- name: Create grafana config
  template:
    src: grafana-custom-ini.j2
    dest: /usr/local/share/dodasts/monitoring/grafana/config/custom.ini

- name: get client id and secret
  shell:
    cmd: |
      chmod +x /usr/local/share/dodasts/monitoring/grafana/utils/get_client \
      && /usr/local/share/dodasts/monitoring/grafana/utils/get_client {{iam_url}} {{server_ip}} {{grafana_port}}
  when: grafana_client_id == "CLIENT_ID" and grafana_client_secret == "CLIENT_SECRET"

- name: prepare variables for monitoring
  set_fact:
    key_value: "yes"
    grafana_service: |
      grafana:
          image: grafana/grafana:latest
          container_name: monitoring_grafana
          depends_on:
            - prometheus
          restart: unless-stopped
          command:
            - "-config"
            - "/opt/grafana/custom.ini"
          ports:
            - 3000:3000
          volumes:
            - /tmp/certs/grafana:/tmp/certs/grafana
            - /usr/local/share/dodasts/monitoring/grafana/config:/opt/grafana/
            - /usr/local/share/dodasts/monitoring/grafana/config/provisioning:/etc/grafana/provisioning
            - /usr/local/share/dodasts/monitoring/grafana/dash_models:/opt/dash_models
          environment:
            - GF_SECURITY_ADMIN_USER={{grafana_admin_user}}
            - GF_SECURITY_ADMIN_PASSWORD={{grafana_admin_password}}
            - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true
            - GF_USERS_ALLOW_SIGN_UP=false
    cacheable: yes
