---
- name: download jupyterhub
  shell: git clone {{ jupyter_repo_url }} /usr/local/share/dodasts/jupyterhub
  args:
    creates:
      - /usr/local/share/dodasts/jupyterhub
  when: (not (jupyterhub_collaborative | bool))

- name: "download jupyterhub + collaborative service"
  shell: git clone -b collaborative {{ jupyter_repo_url }} /usr/local/share/dodasts/jupyterhub
  args:
    creates:
      - /usr/local/share/dodasts/jupyterhub
  when: (jupyterhub_collaborative | bool)

- name: create JUPYTERHUB_API_TOKEN
  shell: openssl rand -hex 32
  register: jupyterhub_api_token
  when: (jupyterhub_collaborative | bool)

- name: create JUPYTER_TOKEN
  shell: openssl rand -hex 32
  register: jupyter_token
  when: (jupyterhub_collaborative | bool)

- name: add jupyterlab collaborative dependency
  set_fact:
    key_value: "yes"
    jupyterlab_collaborative_image_param: "image: {{ jupyterlab_collaborative_image }}"
  when: ((jupyterhub_collaborative | bool ) and jupyterlab_collaborative_image != "")

- name: prepare collaborative jupyterlab
  set_fact:
    key_value: "yes"
    jupyterlab_collaborative_service: |
      collab_proxy:
        build: collab_proxy
        environment:
          - JUPYTERHUB_BASE_URL=http://jupyterhub:{{ jupyter_port }}
          - JUPYTERHUB_API_URL=http://jupyterhub:{{ jupyter_port }}/hub/api
          - JUPYTERHUB_SERVICE_PREFIX=/services/collab/
          - JUPYTERHUB_API_TOKEN={{jupyterhub_api_token.stdout | string}}
          - JUPYTER_TOKEN={{ jupyter_token.stdout | string }}
        ports:
          - 8099:8099

      jupyterlab_collab:
        {{ jupyterlab_collaborative_image_param }}
        volumes:
            - /tmp/certs/jupyter:/tmp/certs/jupyter
            - /usr/local/share/collabspace/:/usr/share/workspace
        environment:
            - JUPYTER_TOKEN={{ jupyter_token.stdout | string }}
        ports:
          - 8889:8888

    cacheable: yes
  when: (jupyterhub_collaborative | bool)

- name: add jupyterlab collaborative dependency
  set_fact:
    key_value: "yes"
    jupyterlab_collaborative_service_dependency: "- collab_proxy"
  when: (jupyterhub_collaborative | bool)

- name: "change token in jupyterhub"
  replace:
    path: /usr/local/share/dodasts/jupyterhub/jupyterhub_config.py
    regexp: 'c\.ConfigurableHTTPProxy\.auth_token[a-zA-Z\ \=\"\_]*'
    replace: 'c.ConfigurableHTTPProxy.auth_token = "{{ jupyter_proxy_token }}"'

- name: "change image in jupyterhub"
  replace:
    path: /usr/local/share/dodasts/jupyterhub/jupyterhub_config.py
    regexp: '\<datalist\ id\=\"images\"\>[\n\t\ \<\>\=\"\/\_\:\-0-9a-zA-Z]*<\/datalist\>'
    replace: |
      <datalist id="images">
      {{ jupyter_images.split() | join('\n') }}
      </datalist>

- name: "insert image list"
  lineinfile:
    path: /usr/local/share/dodasts/jupyterhub/jupyterhub_config.py
    regexp: "{{ item }}"
    line: <option value="{{ item }}">{{ item|upper }}</option>
  with_items: "{{ jupyter_images.split() }}"

- name: ram size
  debug:
    var: ansible_facts.memtotal_mb

- name: create ram giga var
  set_fact:
    key_value: "yes"
    cacheable: yes
    ram_giga: "{{ ((ansible_facts.memtotal_mb|int) / 1000)|int }}"

- name: create ram list
  set_fact:
    key_value: "yes"
    cacheable: yes
    list_ram_sizes: "{{ [1] + range(2, (ram_giga|int) + 1, 2) | list }}"

- name: result ram list
  debug:
    var: list_ram_sizes

- name: create ram list placeholders
  set_fact:
    key_value: "yes"
    cacheable: yes
    list_ram_size_placeholders: "{{ list_ram_sizes | product(['G']) | map('join', '') | list }}"

- name: ram list placeholders
  debug:
    var: list_ram_size_placeholders

- name: "change ram size in jupyterhub"
  replace:
    path: /usr/local/share/dodasts/jupyterhub/jupyterhub_config.py
    regexp: '\<\!\-\-\ MEM\ START\ \-\-\>[\n\t\ \<\>\=\"\/\_\:\-0-9a-zA-Z]*\<\!\-\-\ MEM\ END\ \-\-\>'
    replace: |
      <!-- MEM START -->
      <select name="mem" size="1">
        {{ ['ram-size-'] | product(list_ram_size_placeholders) | map('join', '') | join('\n') }}
      </select>
      <!-- MEM END -->

- name: "insert ram size list"
  lineinfile:
    path: /usr/local/share/dodasts/jupyterhub/jupyterhub_config.py
    regexp: "ram-size-{{ item }}"
    line: <option value="{{ item }}">{{ item }}B</option>
  with_items: "{{ list_ram_size_placeholders }}"

# ---------- Create directory for jupyterhub ----------
- name: Create directory for jupyterhub
  file:
    path: /usr/local/share/dodasts/jupyterhub
    state: directory
    mode: 0755

- name: Create directory for jupyterhub cookies
  file:
    path: /usr/local/share/dodasts/jupyterhub/cookies
    state: directory
    mode: 0755

- name: Create directory for jupyterhub db
  file:
    path: /usr/local/share/dodasts/jupyterhub/db
    state: directory
    mode: 0755

- name: "prepare variables for jupyter"
  set_fact:
    key_value: "yes"
    jupyter_gpu: "WITH_GPU=true"
    cacheable: yes
  when: (use_gpu | bool)

- name: prepare compose file
  template:
    src: jupyter_hub-compose.j2
    dest: /usr/local/share/dodasts/jupyterhub/docker-compose.yaml

# finally pre-cache default images
- name: pull images
  command: docker pull "{{ item }}"
  with_items: "{{ jupyter_images.split() }}"
