---
- name: download MLinD-INFN
  git:
    repo: "https://github.com/dodas-ts/MLinD-INFN"
    dest: /usr/local/share/MLinD-INFN
    force: yes

- name: "prepare variables for jupyter"
  set_fact:
    key_value: "yes"
    jupyter_gpu: "true"
    cacheable: yes
  when: (use_gpu | bool)

- name: prepare compose file
  template:
    src: jupyter_hub-compose.j2
    dest: /usr/local/share/MLinD-INFN/docker-compose.yaml
