---
- name: download MLinD-INFN
  git:
    repo: "https://github.com/dodas-ts/MLinD-INFN"
    dest: /usr/local/share/MLinD-INFN
    force: yes

- name: "change token in jupyterhub"
  replace:
    path: /usr/local/share/MLinD-INFN/jupyterhub_config.py
    regexp: 'c\.ConfigurableHTTPProxy\.auth_token[a-zA-Z\ \=\"\_]*'
    replace: 'c.ConfigurableHTTPProxy.auth_token = "{{jupyter_proxy_token}}"'

- name: "change image in jupyterhub"
  replace:
    path: /usr/local/share/MLinD-INFN/jupyterhub_config.py
    regexp: '\<datalist\ id\=\"images\"\>[\n\t\ \<\>\=\"\/\_\:\-0-9a-zA-Z]*<\/datalist\>'
    replace: '<datalist id="images"><option value="{{jupyter_image}}">{{jupyter_image|upper}}</option></datalist>'

# ---------- Create directory for jupyterhub ----------
- name: Create directory for jupyterhub
  file:
    path: /usr/local/share/jupyterhub
    state: directory
    mode: 0755

- name: Create directory for jupyterhub cookies
  file:
    path: /usr/local/share/jupyterhub/cookies
    state: directory
    mode: 0755

- name: Create directory for jupyterhub db
  file:
    path: /usr/local/share/jupyterhub/db
    state: directory
    mode: 0755

- name: "prepare variables for jupyter"
  set_fact:
    key_value: "yes"
    jupyter_gpu: "WITH_GPU=true"
    cacheable: yes
  when: (use_gpu | bool)

- name: prepare compose file
  template:
    src: jupyter_hub-compose.j2
    dest: /usr/local/share/MLinD-INFN/docker-compose.yaml
